### ISSUE TITLE
多用户怎么配置？

### ISSUE THREAD

**Issue by Junya520** [simo8102/88-AutoSignMachine#1]
老哥多用户怎么配置？

**Comment by DouGe372** [comment]
> 老哥多用户怎么配置？

暂时没有啊。

**Comment by simo8102** [comment]
可以搞的哦

**Comment by simo8102** [comment]
https://github.com/你的用户名/88-AutoSignMachine/settings/secrets/actions 然后点击New repository secret
上面输入config
下面输入这个
{
    "accountSn": "1,2",
    "user-1": "22******1",
    "password-1": "31******1",
    "appid-1": "41******1",
    "user-2": "25******1",
    "password-3": "72******1",
    "appid-2": "92******1"
}


然后在自动脚本里把最后一句删了改成下面这两句
echo ${{secrets.unicom_config}} >> config.json
 run: node index.js unicom -config config.json

**Comment by DouGe372** [comment]
6666表哥。有的活动是不是改了API了

**Comment by lfmwuy** [comment]
自动脚本是哪个文件

**Comment by zcmy321** [comment]
可不可以三用户？

**Comment by zcmy321** [comment]
> [https://github.com/你的用户名/88-AutoSignMachine/settings/secrets/actions](https://github.com/%E4%BD%A0%E7%9A%84%E7%94%A8%E6%88%B7%E5%90%8D/88-AutoSignMachine/settings/secrets/actions) 然后点击New repository secret
> 上面输入config
> 下面输入这个
> {
> "accountSn": "1,2",
> "user-1": "22******1", "password-1": "31******1",
> "appid-1": "41******1", "user-2": "25******1",
> "password-2": "72******1", "appid-2": "92******1"
> }
> 
> 然后在自动脚本里把最后一句删了改成下面这两句
> config: ${{secrets.CONFIG}}
> run: |
> echo "$config" > ./config.json
> node index.js unicom --config config.json

可以三用户吗？

**Comment by handsomebubu** [comment]
**新版本有以下的报错。**

总账户数 2
[❌🤣🌋] (node:1730) UnhandledPromiseRejectionWarning: TypeError: scheduler.taskKey.replaceWithMask is not a function
    at Object.hasWillTask (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/scheduler.js:240:47)
    at /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/unicom.js:50:38
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
[❌🤣🌋] (node:1730) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[❌🤣🌋] (node:1730) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[❌🤣🌋] (node:1730) UnhandledPromiseRejectionWarning: TypeError: scheduler.taskKey.replaceWithMask is not a function
    at Object.hasWillTask (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/scheduler.js:240:47)
    at /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/unicom.js:50:38
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
[❌🤣🌋] (node:1730) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
