### ISSUE TITLE
短信验证码登录

### ISSUE THREAD

**Issue by xiaohei2333** [simo8102/88-AutoSignMachine#110]
******409 作为账户识别码
获得配置文件 /home/runner/.AutoSignMachine/taskFile_unicom_13******409.json 当前日期 20210411
任务配置文件不存在，创建配置中
计算可执行任务 总任务数 26 已完成任务数 0 错误任务数 0 指定任务数 0 预计可执行任务数 14
开始执行任务
dailysignin: cookies凭据访问失败，将使用账户密码登录
dailysignin: 登陆失败:尊敬的客户您好，请使用短信验证码登录进行身份验证!
dailysignin: [❌🤣🌋] unicom任务: Error: 登陆失败:尊敬的客户您好，请使用短信验证码登录进行身份验证!
    at module.exports (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/init.js:111:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.init (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/unicom.js:9:5)
    at async Object.execTask (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/scheduler.js:280:74)
    at async /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/unicom.js:56:9
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
dailysignin: 当前任务执行完毕！

这怎么解啊老哥们

**Comment by simo8102** [comment]
没碰到过  建议重新抓个appid

**Comment by xiaohei2333** [comment]
> 没碰到过建议重新抓个appid

谢谢老哥   重新弄了个appid就能用了
