### ISSUE TITLE
请问为何有时任务执行总不成功

### ISSUE THREAD

**Issue by keaimao1989** [simo8102/88-AutoSignMachine#117]
最近几天任务执行总不成功，运行20.30分钟就停下来了，非得白天醒来后手动运行一下才可以。进去看日志，如下：

开始执行任务
dailysignin: 获得登录状态成功
exchangeDFlow: 调度任务中 并发数 1
dailysignin: 延迟执行 dailysignin 20 seconds
dailysignin: 任务错误： ReferenceError: result is not defined
    at Object.getIntegral (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/dailysignin.js:19:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.doTask (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/dailysignin.js:64:29)
    at async Object.<anonymous> (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/unicom.js:23:5)
    at async /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/scheduler.js:315:29
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)

请问是哪里出错了？

**Comment by Kang128** [comment]
半夜系统维护

**Comment by keaimao1989** [comment]
> 半夜系统维护

现在运行时间不是改到早上六点多了？

**Comment by simo8102** [comment]
是的我也遇到了这个问题，还在研究
