### ISSUE TITLE
游戏部分代码执行有错误，好像不是网络问题

### ISSUE THREAD

**Issue by lxr760** [simo8102/88-AutoSignMachine#126]
producGameSignin: 延迟执行 producGameSignin 41 seconds
producGameSignin: 任务错误： /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/producGame.js:386
                }
                ^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/unicom.js:63:11)
    at /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/scheduler.js:315:48
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
producGameSignin: producGameSignin 执行用时 41 秒
dailygameflow: 延迟执行 dailygameflow 15 seconds
dailygameflow: 任务错误： /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/producGame.js:386
                }
                ^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/unicom.js:69:11)
    at /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/scheduler.js:315:48
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
dailygameflow: dailygameflow 执行用时 15 秒

**Comment by simo8102** [comment]
不是网络问题 代码得问题

**Comment by lxr760** [comment]
> 不是网络问题 代码得问题

大佬，我看你刚更新了代码         是不是这下26个游戏都能跑完了？

另外  问下   目前代码好像阅读做完还领不了流量    要用那个exe        能否跑一次代码全部实现呢？
