### ISSUE TITLE
1g流量包兑换失败

### ISSUE THREAD

**Issue by Sumouruge2390** [simo8102/88-AutoSignMachine#145]
exchangeDFlow: 任务错误： TypeError: cards is not iterable
    at Object.querywinninglist (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/exchangeDFlow.js:112:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exchange (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/exchangeDFlow.js:269:28)
    at async Object.doTask (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/exchangeDFlow.js:281:9)
    at async Object.scheduler.regTask (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/unicom.js:289:4)
    at async /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/scheduler.js:315:29
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)

**Comment by Sumouruge2390** [comment]
之前零钱账户有1g兑换方式时手动可以换

**Comment by simo8102** [comment]
已知问题 部分号码会这个错误
