### ISSUE TITLE
有没有ios本地运行的方法

### ISSUE THREAD

**Issue by XDdian66** [simo8102/88-AutoSignMachine#155]
首先感谢大佬辛苦写出的代码！没有了action 电脑也不常用 想问问大佬有没有ios本地运行的方式

**Comment by simo8102** [comment]
苹果好像有个叫ish的软件，你试一下。

**Comment by YANGHAI666** [comment]
> 苹果好像有个叫ish的软件，你试一下。
大佬这是什么问题呢？

安装这个有问题，qd# apk add cronie
ERROR: unsatisfiable constraints:
  cronie (missing):
    required by: world[cronie]

然后跑脚本出现这个
(node:81) UnhandledPromiseRejectionWarning: Error: Cannot find module 'yargs/yargs'
Require stack:
- /root/qd/AutoSignMachine.js
- /root/qd/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/qd/AutoSignMachine.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
(node:81) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:81) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by XDdian66** [comment]
啊这 一点也用不明白

**Comment by zmnsQ** [comment]
我用ish安装npm和node后npm install下载依赖会出错
