### ISSUE TITLE
succeeded 14 hours ago in 26s

### ISSUE THREAD

**Issue by qian9008** [simo8102/88-AutoSignMachine#66]
啥都没干就成功了。。。到底怎么用呢

**Comment by qian9008** [comment]
ENABLE_UNICOM （true）

unicom_password（123456）

unicom_user（13333333333）

unicom_appid（herhmowpingwopiuthoe)
是这样填吗

**Comment by simo8102** [comment]
说明不是写的很详细吗 第一个其实可以不填

**Comment by Blender-S** [comment]
多账号的设置能不能像跟填写一个账号那样操作啊

**Comment by qian9008** [comment]
> 说明不是写的很详细吗 第一个其实可以不填

我就是这样填的啊 但是appid 出错

**Comment by qian9008** [comment]
> > 说明不是写的很详细吗 第一个其实可以不填
> 
> 我就是这样填的啊 但是appid 出错

开始执行任务
dailysignin: cookies凭据访问失败，将使用账户密码登录
dailysignin: [❌🤣🌋] unicom任务: Error: 需要提供appid
    at module.exports (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/init.js:69:13)
    at Object.init (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/unicom.js:9:28)
    at Object.execTask (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/scheduler.js:280:98)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/unicom.js:56:9
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
dailysignin: 今日获得奖品信息统计
dailysignin: 当前任务执行完毕！

**Comment by qian9008** [comment]
终于可以了，之前用其他程序 ，密钥只要一个包含所有内容，所以理解错误了。谢谢！
