### ISSUE TITLE
3G流量最后一个任务无法完成

### ISSUE THREAD

**Issue by nameIsWenZhiyi** [simo8102/88-AutoSignMachine#75]
3G流量最后一个任务无法完成，为什么

**Comment by Yuan-Hang** [comment]
借楼问问，我在联通app游戏领取页面只有20个游戏呢？这样算只有2G流量，还有1G在哪儿领取

**Comment by axh2018** [comment]
20个游戏+1，只有2G

**Comment by tanzl** [comment]
把**producGame.js**的`doGameFlowTask`，`timeTaskQuery`，`doTodayDailyTask`这几个方法修改下就没问题了，能自动领取流量。
```javascript
doGameFlowTask: async (axios, options) => {
        let { popularList: allgames, jar } = await producGame.popularGames(axios, options)
        let games = allgames.filter(g => g.state === '0')
        console.info('剩余未完成game', games.length)
        let queue = new PQueue({ concurrency: 2 });

        console.info('调度任务中', '并发数', 2)
        for (let game of games) {
            queue.add(async () => {
                console.info(game.name)
                if (game.qqMark === "N") {
                    await require('./xiaowogameh5').playGame(axios, {
                        ...options,
                        game
                    })
                } else {
                    await producGame.gameverify(axios, {
                        ...options,
                        jar,
                        game
                    })
                    await producGame.playGame(axios, {
                        ...options,
                        jar,
                        game
                    })
                }
            })
        }

        await queue.onIdle()

        await new Promise((resolve, reject) => setTimeout(resolve, (Math.floor(Math.random() * 10) + 30) * 1000))
        games = await producGame.timeTaskQuery(axios, options)
        games = games.filter(g => g.state === '1')
        console.info('剩余未领取game', games.length)
        for (let game of games) {
            await new Promise((resolve, reject) => setTimeout(resolve, (Math.floor(Math.random() * 10) + 15) * 1000))
            await producGame.gameFlowGet(axios, {
                ...options,
                gameId: game.id
            })
        }
    },
```
```javascript
timeTaskQuery: async (axios, options) => {
        const useragent = buildUnicomUserAgent(options, 'p')
        let params = {
            'methodType': 'timeTaskQuery',
            'deviceType': 'Android',
            'clientVersion': appInfo.version
        }
        let { data } = await axios.request({
            baseURL: 'https://m.client.10010.com/',
            headers: {
                "user-agent": useragent,
                "referer": "https://img.client.10010.com",
                "origin": "https://img.client.10010.com"
            },
            url: `/producGameApp`,
            method: 'post',
            data: transParams(params)
        })
        if (data) {
            console.info(data.msg)
            let {popularList} = await producGame.popularGames(axios, options)
            return popularList;
        } else {
            console.error('记录失败')
        }
    },
```
```javascript
doTodayDailyTask: async (axios, options) => {

        /* let { games: v_games } = await producGame.getTaskList(axios, options)
        let video_task = v_games.find(d => d.task_type === 'video')

        if (video_task.reachState === '0') {
            let n = parseInt(video_task.task) - parseInt(video_task.progress)
            console.info('领取视频任务奖励,剩余', n, '次')
            let { jar } = await producGame.watch3TimesVideoQuery(axios, options)
            let i = 1
            while (i <= n) {
                await producGame.watch3TimesVideo(axios, {
                    ...options,
                    jar
                })
                await new Promise((resolve, reject) => setTimeout(resolve, (Math.floor(Math.random() * 5) + 2) * 200))
                await producGame.getTaskList(axios, options)
                await producGame.queryIntegral(axios, {
                    ...options,
                    taskCenterId: video_task.id
                })
                ++i
            }
        } */

        let { games } = await producGame.getTaskList(axios, options)
        let today_task = games.find(d => d.task_type === 'todayTask')
        if (!today_task) {
            console.info('未取得今日任务，跳过')
            return
        }
        if (today_task.reachState === '0') {
            throw new Error('部分日常任务未完成，下次再尝试领取完成今日任务流量')
        } else if (today_task.reachState === '1') {
            await producGame.gameIntegralGet(axios, {
                ...options,
                taskCenterId: today_task.id
            })
            console.reward('flow', '100m')
            console.info('领取完成今日任务流量+100m')
        } else if (today_task.reachState === '2') {
            console.info('每日日常任务已完成')
        }
    }
```

**Comment by simo8102** [comment]
> 把**producGame.js**的`doGameFlowTask`，`timeTaskQuery`，`doTodayDailyTask`这几个方法修改下就没问题了，能自动领取流量。
> 
> ```js
> doGameFlowTask: async (axios, options) => {
>         let { popularList: allgames, jar } = await producGame.popularGames(axios, options)
>         let games = allgames.filter(g => g.state === '0')
>         console.info('剩余未完成game', games.length)
>         let queue = new PQueue({ concurrency: 2 });
> 
>         console.info('调度任务中', '并发数', 2)
>         for (let game of games) {
>             queue.add(async () => {
>                 console.info(game.name)
>                 if (game.qqMark === "N") {
>                     await require('./xiaowogameh5').playGame(axios, {
>                         ...options,
>                         game
>                     })
>                 } else {
>                     await producGame.gameverify(axios, {
>                         ...options,
>                         jar,
>                         game
>                     })
>                     await producGame.playGame(axios, {
>                         ...options,
>                         jar,
>                         game
>                     })
>                 }
>             })
>         }
> 
>         await queue.onIdle()
> 
>         await new Promise((resolve, reject) => setTimeout(resolve, (Math.floor(Math.random() * 10) + 30) * 1000))
>         games = await producGame.timeTaskQuery(axios, options)
>         games = games.filter(g => g.state === '1')
>         console.info('剩余未领取game', games.length)
>         for (let game of games) {
>             await new Promise((resolve, reject) => setTimeout(resolve, (Math.floor(Math.random() * 10) + 15) * 1000))
>             await producGame.gameFlowGet(axios, {
>                 ...options,
>                 gameId: game.id
>             })
>         }
>     },
> ```
> 
> ```js
> timeTaskQuery: async (axios, options) => {
>         const useragent = buildUnicomUserAgent(options, 'p')
>         let params = {
>             'methodType': 'timeTaskQuery',
>             'deviceType': 'Android',
>             'clientVersion': appInfo.version
>         }
>         let { data } = await axios.request({
>             baseURL: 'https://m.client.10010.com/',
>             headers: {
>                 "user-agent": useragent,
>                 "referer": "https://img.client.10010.com",
>                 "origin": "https://img.client.10010.com"
>             },
>             url: `/producGameApp`,
>             method: 'post',
>             data: transParams(params)
>         })
>         if (data) {
>             console.info(data.msg)
>             let {popularList} = await producGame.popularGames(axios, options)
>             return popularList;
>         } else {
>             console.error('记录失败')
>         }
>     },
> ```
> 
> ```js
> doTodayDailyTask: async (axios, options) => {
> 
>         /* let { games: v_games } = await producGame.getTaskList(axios, options)
>         let video_task = v_games.find(d => d.task_type === 'video')
> 
>         if (video_task.reachState === '0') {
>             let n = parseInt(video_task.task) - parseInt(video_task.progress)
>             console.info('领取视频任务奖励,剩余', n, '次')
>             let { jar } = await producGame.watch3TimesVideoQuery(axios, options)
>             let i = 1
>             while (i <= n) {
>                 await producGame.watch3TimesVideo(axios, {
>                     ...options,
>                     jar
>                 })
>                 await new Promise((resolve, reject) => setTimeout(resolve, (Math.floor(Math.random() * 5) + 2) * 200))
>                 await producGame.getTaskList(axios, options)
>                 await producGame.queryIntegral(axios, {
>                     ...options,
>                     taskCenterId: video_task.id
>                 })
>                 ++i
>             }
>         } */
> 
>         let { games } = await producGame.getTaskList(axios, options)
>         let today_task = games.find(d => d.task_type === 'todayTask')
>         if (!today_task) {
>             console.info('未取得今日任务，跳过')
>             return
>         }
>         if (today_task.reachState === '0') {
>             throw new Error('部分日常任务未完成，下次再尝试领取完成今日任务流量')
>         } else if (today_task.reachState === '1') {
>             await producGame.gameIntegralGet(axios, {
>                 ...options,
>                 taskCenterId: today_task.id
>             })
>             console.reward('flow', '100m')
>             console.info('领取完成今日任务流量+100m')
>         } else if (today_task.reachState === '2') {
>             console.info('每日日常任务已完成')
>         }
>     }
> ```

感谢兄弟提供的思路，你看下能不能提交个pr

**Comment by tanzl** [comment]
@simo8102 pr提了，你运行看下。

**Comment by Yuan-Hang** [comment]
@simo8102  最新的代码执行遇到错误，大佬看下是什么情况呢：


dailygameflow: [❌🤣🌋] Error: 出现网络超时错误
    at axiosRetryInterceptor (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/utils/request.js:89:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.openPlatLine (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/xiaowogameh5.js:78:19)
    at async Object.playGame (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/xiaowogameh5.js:160:30)
    at async /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/producGame.js:372:21
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
dailygameflow: 三国战
dailygameflow: [❌🤣🌋] (node:1672) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at Object.playGame (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/xiaowogameh5.js:164:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/runner/work/88-AutoSignMachine/88-AutoSignMachine/commands/tasks/unicom/producGame.js:372:21
    at async run (/home/runner/work/88-AutoSignMachine/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
dailygameflow: [❌🤣🌋] (node:1672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
dailygameflow: [❌🤣🌋] (node:1672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gzbottle** [comment]
用了最新代码，完美运行并自动领取了，我是本地跑的脚本
