### ISSUE TITLE
不玩游戏 或者不领取

### ISSUE THREAD

**Issue by qian9008** [simo8102/88-AutoSignMachine#87]
前天自动玩游戏的，我自己手动app领的流量。昨天发现没玩游戏 ，手动运行一次正常玩游戏了，今天看昨天流量没有自动领取。
计算可执行任务 总任务数 34 已完成任务数 0 错误任务数 0 指定任务数 0 预计可执行任务数 3
开始执行任务
producGameSignin: 获得登录状态成功
exchangeDFlow: 调度任务中 并发数 1
producGameSignin: 延迟执行 producGameSignin 10 seconds
producGameSignin: [❌🤣🌋] 获取游戏任务失败
producGameSignin: 任务错误： TypeError: Cannot read property 'find' of undefined
    at Object.gameBox (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/producGame.js:550:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.<anonymous> (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/unicom.js:200:5)
    at async /home/runner/work/nMachine/nMachine/utils/scheduler.js:315:29
    at async run (/home/runner/work/nMachine/nMachine/node_modules/p-queue/dist/index.js:163:29)
producGameSignin: producGameSignin 执行用时 10 秒

**Comment by qian9008** [comment]
各式各样的报错  很多
hfgo: [❌🤣🌋] Error: 出现网络超时错误
    at axiosRetryInterceptor (/home/runner/work/nMachine/nMachine/utils/request.js:89:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.openPlatLine (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/hfgo.js:14:22)
    at async Object.doTask (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/hfgo.js:181:37)
    at async Object.<anonymous> (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/unicom.js:364:5)
    at async /home/runner/work/nMachine/nMachine/utils/scheduler.js:315:29
    at async run (/home/runner/work/nMachine/nMachine/node_modules/p-queue/dist/index.js:163:29)
hfgo: 任务错误： TypeError: Cannot read property 'config' of undefined
    at Object.openPlatLine (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/hfgo.js:34:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.doTask (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/hfgo.js:181:37)
    at async Object.<anonymous> (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/unicom.js:364:5)
    at async /home/runner/work/nMachine/nMachine/utils/scheduler.js:315:29
    at async run (/home/runner/work/nMachine/nMachine/node_modules/p-queue/dist/index.js:163:29)
hfgo: hfgo 执行用时 548 秒
exchangeDFlow: 任务错误： TypeError: cards is not iterable
    at Object.querywinninglist (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/exchangeDFlow.js:108:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exchange (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/exchangeDFlow.js:265:28)
    at async Object.doTask (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/exchangeDFlow.js:277:9)
    at async Object.scheduler.regTask (/home/runner/work/nMachine/nMachine/commands/tasks/unicom/unicom.js:387:5)
    at async /home/runner/work/nMachine/nMachine/utils/scheduler.js:315:29
    at async run (/home/runner/work/nMachine/nMachine/node_modules/p-queue/dist/index.js:163:29)
exchangeDFlow: exchangeDFlow 执行用时 6 秒

**Comment by qian9008** [comment]
这个是 夜里00-01点执行2次。不是早晚各一次的意思啊。
- cron: '*/60 16-18 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(4-23)

**Comment by simo8102** [comment]
> 这个是 夜里00-01点执行2次。不是早晚各一次的意思啊。
> 
> * cron: '*/60 16-18 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(4-23)

翻译过来不就是凌晨12点和1点各执行一次任务

**Comment by qian9008** [comment]
> > 这个是 夜里00-01点执行2次。不是早晚各一次的意思啊。
> > 
> > * cron: '*/60 16-18 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(4-23)
> 
> 翻译过来不就是凌晨12点和1点各执行一次任务

 我分2行 改成 12-2点 执行2次， 18-20点再每小时执行1次，试试。

**Comment by qian9008** [comment]
多运行了 几次 已经是 1mb 了
