### ISSUE TITLE
如何在自己的服务器上执行？

### ISSUE THREAD

**Issue by etclub** [simo8102/88-AutoSignMachine#88]
我已经参考 default.json，提供了相关信息
然后运行 `node index.js unicom --config ./config.json`

但是直接报错
```
总账户数 1
/home/me/project/88-AutoSignMachine/utils/scheduler.js:240
        console.info('将使用', scheduler.taskKey.replaceWithMask(2, 3), '作为账户识别码')
                                              ^

TypeError: scheduler.taskKey.replaceWithMask is not a function
    at Object.hasWillTask (/home/me/project/88-AutoSignMachine/utils/scheduler.js:240:47)
    at /home/me/project/88-AutoSignMachine/commands/unicom.js:50:38
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async run (/home/me/project/88-AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
```

**Comment by ovenone** [comment]
git pull https://github.com/simo8102/88-AutoSignMachine.git
cd 88-AutoSignMachine/
npm install
node index.js unicom --user 176********* --password ****** --appid *****************

linux   在安装了git和node 情况下直接以上动作 或者做成sh脚本 多账户就在后面添加多个   设置定时任务 每次定时运行时自动与github同步  然后执行动作。。
